#API层通用配置
security:
  oauth2:
    client:
      clientId: yong
      clientSecret: passw0rd
      accessTokenUri: localhost:8081/api/oauth/token
      userAuthorizationUri: localhost:8081/api/oauth/authorize
    resource:
      userInfoUri: http://127.0.0.1:8081/api/user/me


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic