#dev环境通用配置

#数据库的地址应该是env level的，每个env的对应的db地址应该是不一样的
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health